apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
  {{- range $, $config := .Values.deployment.container.ports }}
    - name: {{ $config.name }}
      protocol: {{ $config.protocol }}
      port: {{ $config.servicePort | default $config.containerPort }}
      targetPort: {{ $config.name }}
  {{- end }}
  selector:
    app: {{ .Values.deployment.app }}
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
